// <auto-generated />
using System;
using Fomo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fomo.Infrastructure.Migrations
{
    [DbContext(typeof(EFCoreDbContext))]
    partial class EFCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fomo.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StockId");

                    b.HasIndex("Name");

                    b.HasIndex("Symbol");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Fomo.Domain.Entities.TradeMethod", b =>
                {
                    b.Property<int>("TradeMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TradeMethodId"));

                    b.Property<bool>("Bollinger")
                        .HasColumnType("boolean");

                    b.Property<bool>("Other")
                        .HasColumnType("boolean");

                    b.Property<bool>("Rsi")
                        .HasColumnType("boolean");

                    b.Property<bool>("Sma")
                        .HasColumnType("boolean");

                    b.Property<bool>("Stochastic")
                        .HasColumnType("boolean");

                    b.Property<int>("TradeResultId")
                        .HasColumnType("integer");

                    b.HasKey("TradeMethodId");

                    b.HasIndex("TradeResultId")
                        .IsUnique();

                    b.ToTable("TradeMethods");
                });

            modelBuilder.Entity("Fomo.Domain.Entities.TradeResult", b =>
                {
                    b.Property<int>("TradeResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TradeResultId"));

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("ExitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("NumberOfStocks")
                        .HasColumnType("integer");

                    b.Property<decimal>("Profit")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TradeResultId");

                    b.HasIndex("UserId");

                    b.ToTable("TradeResults", t =>
                        {
                            t.HasCheckConstraint("CK_Product_EntryPrice_NonNegative", "\"EntryPrice\" >= 0");

                            t.HasCheckConstraint("CK_Product_ExitPrice_NonNegative", "\"ExitPrice\" >= 0");

                            t.HasCheckConstraint("CK_Product_NumberOfStocks_NonNegative", "\"NumberOfStocks\" >= 0");
                        });
                });

            modelBuilder.Entity("Fomo.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BollingerAlert")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("RsiAlert")
                        .HasColumnType("boolean");

                    b.Property<bool>("SmaAlert")
                        .HasColumnType("boolean");

                    b.Property<bool>("StochasticAlert")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.HasIndex("Auth0Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Fomo.Domain.Entities.TradeMethod", b =>
                {
                    b.HasOne("Fomo.Domain.Entities.TradeResult", "TradeResult")
                        .WithOne("TradeMethod")
                        .HasForeignKey("Fomo.Domain.Entities.TradeMethod", "TradeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeResult");
                });

            modelBuilder.Entity("Fomo.Domain.Entities.TradeResult", b =>
                {
                    b.HasOne("Fomo.Domain.Entities.User", "User")
                        .WithMany("TradeResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fomo.Domain.Entities.TradeResult", b =>
                {
                    b.Navigation("TradeMethod")
                        .IsRequired();
                });

            modelBuilder.Entity("Fomo.Domain.Entities.User", b =>
                {
                    b.Navigation("TradeResults");
                });
#pragma warning restore 612, 618
        }
    }
}
